In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])


In [5]:
a

array([1, 2, 3])

In [6]:
b

array([[1, 2],
       [3, 4]])

In [7]:
b.shape


(2, 2)

In [8]:
b.ndim


2

In [9]:
a.size


3

In [11]:
a.dtype

dtype('int64')

In [12]:
a[0]

np.int64(1)

In [13]:
#todas as linhas da coluna 1
b[:,1] 

array([2, 4])